# Base Local Planner Parameters (Pioneer3-DX)
TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_x:                  0.750
  acc_lim_y:                  0.750
  # acc_lim_theta:            3.200 
  max_vel_x:                  0.500
  min_vel_x:                  0.212
  max_vel_theta:              0.100
  # min_vel_theta:           -0.100 
  min_in_place_vel_theta:     0.150
  # escape_vel:              -0.100 
  holonomic_robot:            false

  # Goal Tolerance Parameters
  yaw_goal_tolerance:         0.200
  xy_goal_tolerance:          0.200
  # latch_xy_goal_tolerance:  false

  # Forward Simulation Parameters
  sim_time:                   1.700
  # sim_granularity:          0.025
  # angular_sim_granularity:  0.025
  # vx_samples:               3    
  # vtheta_samples:           20   
  # controller_frequency:     20   

  # Trajectory Scoring Parameters
  meter_scoring: true
  # pdist_scale:              0.6
  # gdist_scale:              0.8
  # occdist_scale:            0.01
  # heading_lookahead:        0.325
  # heading_scoring:          false
  # heading_scoring_timestep: 0.8
  # dwa:                      true
  # publish_cost_grid_pc:     false
  # global_frame_id:          odom

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  
  # Global Plan Parameters
  # prune_plan:               true